steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend:latest"]
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["rollout", "restart", "deployment/backend"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-west9-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=your-cluster"
